#################################################################
# Параметры настройки API
#################################################################
# Протокол обмена API
PROTOCOL="https"
# Сервер API
SERVER="servername"
# Каталог API
CATALOG="/catalogapi/"
# План запуска REST-запросов
REQUEST_PLAN = "schemes/api_request_plan.json"
# Проверять ли подписан сертификат
SSL_VERIFY = 'True'

#################################################################
# Параметры настройки каталога Интерфейса
#################################################################
# Каталог для файлов json, с описанием схемы конвертации
SCHEMES_JSON_DATA_FOLDER = 'schemes/json'
# Каталог, где записываются файлы для отправки
ARCHIVES_FOLDER = 'archives'
# Путь к файлу с конфигурацией
CONF_FILENAME = 'archives'
# Пусть к каталогу исходящих файлов
OUTBOX_DATA_FOLDER="data/outbox"
# Пусть к каталогу входящих файлов
INBOX_DATA_FOLDER="data/inbox"
# Пусть к каталогу обработанных исходящих файлов
ARCHIVE_OUTBOX_DATA_FOLDER="archives/outbox"
# Пусть к каталогу обработанных входящих файлов
ARCHIVE_INBOX_DATA_FOLDER="archives/inbox"
# Путь к каталогу файлов с описанием ошибок
ERRORS_FOLDER="errors"
# Имя файла лога
LOG_FILE = "interface.log"

#################################################################
# Параметры настройки файлов Интерфейса
#################################################################

# Разделитель постфикса файла
POSTFIX_FILENAME_SEPARATOR = "_"
# Разделитель зависимых таблиц в имени файла (Не должно быть пустым)
DEPENDENT_FILENAME_SEPARATOR = ":"
# Разделитель столбца таблицы в файле
COL_SEPARATOR_TABLE="|"
# Перемещать ли файлы в архив
FILES_MOVE_TO_ARCHIVE="YES"
# Формат даты для постфикса
POSTFIX_DATE_FORMAT="_%Y-%m-%d_%H-%M-%S"

#################################################################
# Параметры получения обновления обновления
#################################################################
WORK_COPY_PATH = "."
SVN_PROTOCOL = "https"
SVN_HOST = "host"
SVN_PATH = "path"
SVN_LOGIN = "login"
SVN_PASSW = "password"

